---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.alpha.kubernetes.io/external: {{ .Values.dnsHostName }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: kolide-fleet
  name: kolide-fleet-ext-svc
  namespace: fleet
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: {{ .Values.fleetSvcNodePort }}
      port: {{ .Values.fleetSvcExtPort }}
      protocol: TCP
      targetPort: {{ .Values.fleetSvcTargetPort }}
  selector:
    app: kolide-fleet
  sessionAffinity: None
  type: LoadBalancer
---