---
apiVersion: v1
kind: Secret
metadata:
  name: sslcert
  namespace: fleet
  labels:
    app: fleet
data:
  server-cert.pem: {{ .Values.fleet_cert | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sslkey
  namespace: fleet
  labels:
    app: fleet
data:
  server-key.pem: {{ .Values.fleet_private_key | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sslparentca
  namespace: fleet
  labels:
    app: fleet
data:
  server-key.pem: {{ .Values.fleet_parent_ca | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: fleet-secrets
  namespace: fleet
  labels:
    app: fleet
data:
  fleet-server-auth-key: {{ .Values.fleet_authkey | b64enc | quote  }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: fleet
  labels:
    app: fleet
data:
  redispass: {{ .Values.redispass | b64enc | quote  }}
type: Opaque
---
