---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kolide-fleet
  name: fleet
  namespace: fleet
spec:
  ports:
  - name: kolide-fleet
    port: 2024
    protocol: TCP
    targetPort: 2024
  selector:
    app: fleet-mysql
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kolide-fleet
  name: mailhog
  namespace: fleet
spec:
  ports:
  - name: mail
    port: 1025
    protocol: TCP
    targetPort: 1025
  - name: web
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    app: kolide-fleet
  type: NodePort
---