---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleet-redis
  name: redis-cluster
  namespace: fleet
spec:
  ports:
  - name: redis-cluster
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: fleet-redis
  sessionAffinity: None
---
